version: "3.9"
services:
  sound-server:
    image: "registry.digitalocean.com/my-private-docker/f1f8f7990e1518f5c3bc408318cca8137a6e05ea8486c488a99a0c4fe3b579b5/skps:latest"
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "5000:5000"
  postgres:
    image: "postgres:13.3"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
    volumes:
      - ./db-data:/var/lib/postgresql/data
